Config = {}

Config.SpawnZombie = 1
Config.MinSpawnDistance = 25
Config.MaxSpawnDistance = 75
Config.DespawnDistance = 100

Config.ZombieDropLoot = true
Config.ProbabilityWeaponLoot = 1
Config.ProbabilityMoneyLoot = 40
Config.ProbabilityItemLoot = 50

Config.WeaponLoot = {
	--[["WEAPON_PISTOL",
	"WEAPON_FLASHLIGHT",
	"WEAPON_MACHETE",
	"WEAPON_NIGHTSTICK",
	"WEAPON_BAT",
	"WEAPON_STUNGUN",
	"WEAPON_MICROSMG",
	"WEAPON_PUMPSHOTGUN",
	"WEAPON_ASSAULTRIFLE",
	"WEAPON_SPECIALCARBINE",
	"WEAPON_SNIPERRIFLE",
	"WEAPON_FIREWORK",
	"WEAPON_GRENADE",
	"WEAPON_BZGAS",
	"WEAPON_SMOKEGRENADE",
	"WEAPON_FIREEXTINGUISHER",]]
	"WEAPON_BALL"
}

Config.ItemLoot = {
 --[[	"yusuf",
	"grip",
	"flashlight",
	"suppressor",
	"binoculars",
	"bulletproof",
	"boxpistol",
	"boxsmg",
	"boxshot",
	"boxrifle",
	"boxflare",
	"oxygenmask",
	"repairkit",
	"boxsniper",
	"boxmg",
    'bandage',
	'bandage2',
	'medikit',
	'bruiser',
	'bruiser2',
	'bruiser3',
	'brutus',
	'brutus2',
	'brutus3',
	'deathbike',
	'deathbike2',
	'deathbike3',
	'deviant',
	'impaler',
	'impaler2',
	'impaler3',
	'impaler4',
	'imperator',
	'imperator2',
	'imperator3',
	'issi4',
	'issi5',
	'issi6',
	'monster3',
	'monster4',
	'monster5',
	'slamvan4',
	'slamvan5',
	'slamvan6',
	'tulip',
	'vamos',
	'zr380',
	'zr3802',
	'zr3803',
	'dominator4',
	'dominator5',
	'dominator6',
	'cerberus',
	'cerberus2',
	'cerberus3',
	'scarab',
	'scarab2',
	'scarab3',]]
}

Config.ObjectDropLoot = true --false if you experience low performance of server

Config.ObjectsLoot = { -- objects in here can be looted around the map
	"prop_bin_01a",
	"prop_bin_02a",
	"prop_bin_05a",
	"prop_bin_08a",
	"prop_bin_08open",
	"p_dumpster_t",
	"prop_cs_dumpster_01a",
	"prop_dumpster_01a",
	"prop_dumpster_02a",
	"prop_dumpster_02b",
	"prop_dumpster_3a",
	"prop_dumpster_4a",
	"prop_dumpster_4b"
}

Config.ProbabilityWeaponLootObject = 1
Config.ProbabilityMoneyLootObject = 22
Config.ProbabilityItemLootObject = 99 

Config.WeaponLootObject ={ -- not in use
	--[["WEAPON_PISTOL",
	"WEAPON_FLASHLIGHT",
	"WEAPON_MACHETE",
	"WEAPON_NIGHTSTICK",
	"WEAPON_BAT",
	"WEAPON_STUNGUN",
	"WEAPON_MICROSMG",
	"WEAPON_PUMPSHOTGUN",
	"WEAPON_GRENADE",
	"WEAPON_BZGAS",
	"WEAPON_SMOKEGRENADE",
	"WEAPON_FIREEXTINGUISHER",]]
	"WEAPON_BALL",
}

Config.ItemLootObject = { -- not in use
	'bandage',
	'bandage2',
	'medikit',
}

Config.NoPeds = true
Config.MuteAmbience = true
Config.NotHealthRecharge = true

Config.Debug = false

-- S Class

Config.sweaponn = { -- weapon
	
}

Config.sitemm = { -- item
	'2jzengine_blueprint',
	'WEAPON_ADVANCEDRIFLE_blueprint',
	'WEAPON_APPISTOL_blueprint',
	'WEAPON_ASSAULTRIFLE_MK2_blueprint',
	'WEAPON_ASSAULTSHOTGUN_blueprint',
	'WEAPON_ASSUALTRIFLE_blueprint',
	'WEAPON_ASSUALTSMG_blueprint',
	'WEAPON_AUTOSHOTGUN_blueprint',
	'WEAPON_BULLPUPRIFLE_MK2_blueprint',
	'WEAPON_BULLPUPRIFLE_blueprint',
	'WEAPON_BULLPUPSHOTGUN_blueprint',
	'WEAPON_BZGAS_blueprint',
	'WEAPON_CARBINERIFLE_MK2_blueprint',
	'WEAPON_CARBINERIFLE_blueprint',
	'WEAPON_CERAMICPISTOL_blueprint',
	'WEAPON_COMBATMG_MK2_blueprint',
	'WEAPON_COMBATMG_blueprint',
	'WEAPON_COMBATPDW_blueprint',
	'WEAPON_COMBATPISTOL_blueprint',
	'WEAPON_COMBATSHOTGUN_blueprint',
	'WEAPON_COMPACTLAUNCHER_blueprint',
	'WEAPON_COMPACTRIFLE_blueprint',
	'WEAPON_DBSHOTGUN_blueprint',
	'WEAPON_DOUBLEACTION_blueprint',
	'WEAPON_FIREWORK_blueprint',
	'WEAPON_GRENADELAUNCHER_blueprint',
	'WEAPON_GRENADE_blueprint',
	'WEAPON_GUSENBERG_blueprint',
	'WEAPON_HEAVYPISTOL_blueprint',
	'WEAPON_HEAVYSHOTGUN_blueprint',
	'WEAPON_HEAVYSNIPER_blueprint',
	'WEAPON_HOMINGLAUNCHER_blueprint',
	'WEAPON_MACHINEPISTOL_blueprint',
	'WEAPON_MARKSMANPISTOL_blueprint',
	'WEAPON_MARKSMANRIFLE_MK2_blueprint',
	'WEAPON_MARKSMANRIFLE_blueprint',
	'WEAPON_MG_blueprint',
	'WEAPON_MICROSMG_blueprint',
	'WEAPON_MILITARYRIFLE_blueprint',
	'WEAPON_MINIGUN_blueprint',
	'WEAPON_MINISMG_blueprint',
	'WEAPON_MOLOTOV_blueprint',
	'WEAPON_MUSKET_blueprint',
	'WEAPON_NAVYREVOLVER_blueprint',
	'WEAPON_PIPEBOMB_blueprint',
	'WEAPON_PISTOL50_blueprint',
	'WEAPON_PISTOL_blueprint',
	'WEAPON_PROXMINE_blueprint',
	'WEAPON_PUMPSHOTGUN_MK2_blueprint',
	'WEAPON_PUMPSHOTGUN_blueprint',
	'WEAPON_REVOLVER_blueprint',
	'WEAPON_RPG_blueprint',
	'WEAPON_SAWNOFFSHOTGUN_blueprint',
	'WEAPON_SMG_MK2_blueprint',
	'WEAPON_SMG_blueprint',
	'WEAPON_SNIPERRIFLE_blueprint',
	'WEAPON_SNSPISTOL_MK2_blueprint',
	'WEAPON_SNSPISTOL_blueprint',
	'WEAPON_SPEACIALCARBINERIFLE_blueprint',
	'WEAPON_SPECIALCARBINE_MK2_blueprint',
	'WEAPON_STICKYBOMB_blueprint',
	'WEAPON_VINTAGEPISTOL_blueprint',
	'alcohol',
	'antidot',
	'bombshell',
	'bread',
	'cloth',
	'emptybottle',
	'gunpower',
	'heavyshell',
	'mgshell',
	'michelin_tires_blueprint',
	'nos_blueprint',
	'oxygenmask_blueprint',
	'pistol_clip',
	'pistolshell',
	'race_brakes_blueprint',
	'race_suspension_blueprint',
	'race_transmition_blueprint',
	'repairkit_blueprint',
	'rifle_clip',
	'rifleshell',
	'rubber',
	'scrap',
	'shell_oil_blueprint',
	'shotgun_clip',
	'shotgunshell',
	'smg_clip',
	'smgshell',
	'sniper_clip',
	'snipershell',
	'turbo_lvl_1_blueprint',
	'v8engine_blueprint',
	'water',
	'wood',
}

-- A Class

Config.aweaponn = { -- weapon
	
}

Config.aitemm = { -- item
	'2jzengine_blueprint',
	'WEAPON_ADVANCEDRIFLE_blueprint',
	'WEAPON_APPISTOL_blueprint',
	'WEAPON_ASSAULTRIFLE_MK2_blueprint',
	'WEAPON_ASSAULTSHOTGUN_blueprint',
	'WEAPON_ASSUALTRIFLE_blueprint',
	'WEAPON_ASSUALTSMG_blueprint',
	'WEAPON_AUTOSHOTGUN_blueprint',
	'WEAPON_BULLPUPRIFLE_MK2_blueprint',
	'WEAPON_BULLPUPRIFLE_blueprint',
	'WEAPON_BULLPUPSHOTGUN_blueprint',
	'WEAPON_BZGAS_blueprint',
	'WEAPON_CARBINERIFLE_MK2_blueprint',
	'WEAPON_CARBINERIFLE_blueprint',
	'WEAPON_CERAMICPISTOL_blueprint',
	'WEAPON_COMBATMG_MK2_blueprint',
	'WEAPON_COMBATMG_blueprint',
	'WEAPON_COMBATPDW_blueprint',
	'WEAPON_COMBATPISTOL_blueprint',
	'WEAPON_COMBATSHOTGUN_blueprint',
	'WEAPON_COMPACTLAUNCHER_blueprint',
	'WEAPON_COMPACTRIFLE_blueprint',
	'WEAPON_DBSHOTGUN_blueprint',
	'WEAPON_DOUBLEACTION_blueprint',
	'WEAPON_FIREWORK_blueprint',
	'WEAPON_GRENADELAUNCHER_blueprint',
	'WEAPON_GRENADE_blueprint',
	'WEAPON_GUSENBERG_blueprint',
	'WEAPON_HEAVYPISTOL_blueprint',
	'WEAPON_HEAVYSHOTGUN_blueprint',
	'WEAPON_HEAVYSNIPER_blueprint',
	'WEAPON_HOMINGLAUNCHER_blueprint',
	'WEAPON_MACHINEPISTOL_blueprint',
	'WEAPON_MARKSMANPISTOL_blueprint',
	'WEAPON_MARKSMANRIFLE_MK2_blueprint',
	'WEAPON_MARKSMANRIFLE_blueprint',
	'WEAPON_MG_blueprint',
	'WEAPON_MICROSMG_blueprint',
	'WEAPON_MILITARYRIFLE_blueprint',
	'WEAPON_MINIGUN_blueprint',
	'WEAPON_MINISMG_blueprint',
	'WEAPON_MOLOTOV_blueprint',
	'WEAPON_MUSKET_blueprint',
	'WEAPON_NAVYREVOLVER_blueprint',
	'WEAPON_PIPEBOMB_blueprint',
	'WEAPON_PISTOL50_blueprint',
	'WEAPON_PISTOL_blueprint',
	'WEAPON_PROXMINE_blueprint',
	'WEAPON_PUMPSHOTGUN_MK2_blueprint',
	'WEAPON_PUMPSHOTGUN_blueprint',
	'WEAPON_REVOLVER_blueprint',
	'WEAPON_RPG_blueprint',
	'WEAPON_SAWNOFFSHOTGUN_blueprint',
	'WEAPON_SMG_MK2_blueprint',
	'WEAPON_SMG_blueprint',
	'WEAPON_SNIPERRIFLE_blueprint',
	'WEAPON_SNSPISTOL_MK2_blueprint',
	'WEAPON_SNSPISTOL_blueprint',
	'WEAPON_SPEACIALCARBINERIFLE_blueprint',
	'WEAPON_SPECIALCARBINE_MK2_blueprint',
	'WEAPON_STICKYBOMB_blueprint',
	'WEAPON_VINTAGEPISTOL_blueprint',
	'alcohol',
	'antidot',
	'bombshell',
	'bread',
	'cloth',
	'emptybottle',
	'gunpower',
	'heavyshell',
	'mgshell',
	'michelin_tires_blueprint',
	'nos_blueprint',
	'oxygenmask_blueprint',
	'pistol_clip',
	'pistolshell',
	'race_brakes_blueprint',
	'race_suspension_blueprint',
	'race_transmition_blueprint',
	'repairkit_blueprint',
	'rifle_clip',
	'rifleshell',
	'rubber',
	'scrap',
	'shell_oil_blueprint',
	'shotgun_clip',
	'shotgunshell',
	'smg_clip',
	'smgshell',
	'sniper_clip',
	'snipershell',
	'turbo_lvl_1_blueprint',
	'v8engine_blueprint',
	'water',
	'wood',
}

-- B Class

Config.bweaponn = { -- weapon

}

Config.bitemm = { -- item
	'2jzengine_blueprint',
	'WEAPON_ADVANCEDRIFLE_blueprint',
	'WEAPON_APPISTOL_blueprint',
	'WEAPON_ASSAULTRIFLE_MK2_blueprint',
	'WEAPON_ASSAULTSHOTGUN_blueprint',
	'WEAPON_ASSUALTRIFLE_blueprint',
	'WEAPON_ASSUALTSMG_blueprint',
	'WEAPON_AUTOSHOTGUN_blueprint',
	'WEAPON_BULLPUPRIFLE_MK2_blueprint',
	'WEAPON_BULLPUPRIFLE_blueprint',
	'WEAPON_BULLPUPSHOTGUN_blueprint',
	'WEAPON_BZGAS_blueprint',
	'WEAPON_CARBINERIFLE_MK2_blueprint',
	'WEAPON_CARBINERIFLE_blueprint',
	'WEAPON_CERAMICPISTOL_blueprint',
	'WEAPON_COMBATMG_MK2_blueprint',
	'WEAPON_COMBATMG_blueprint',
	'WEAPON_COMBATPDW_blueprint',
	'WEAPON_COMBATPISTOL_blueprint',
	'WEAPON_COMBATSHOTGUN_blueprint',
	'WEAPON_COMPACTRIFLE_blueprint',
	'WEAPON_DBSHOTGUN_blueprint',
	'WEAPON_DOUBLEACTION_blueprint',
	'WEAPON_GRENADE_blueprint',
	'WEAPON_GUSENBERG_blueprint',
	'WEAPON_HEAVYPISTOL_blueprint',
	'WEAPON_HEAVYSHOTGUN_blueprint',
	'WEAPON_HEAVYSNIPER_blueprint',
	'WEAPON_MACHINEPISTOL_blueprint',
	'WEAPON_MARKSMANPISTOL_blueprint',
	'WEAPON_MARKSMANRIFLE_MK2_blueprint',
	'WEAPON_MARKSMANRIFLE_blueprint',
	'WEAPON_MG_blueprint',
	'WEAPON_MICROSMG_blueprint',
	'WEAPON_MILITARYRIFLE_blueprint',
	'WEAPON_MOLOTOV_blueprint',
	'WEAPON_MUSKET_blueprint',
	'WEAPON_NAVYREVOLVER_blueprint',
	'WEAPON_PIPEBOMB_blueprint',
	'WEAPON_PISTOL50_blueprint',
	'WEAPON_PISTOL_blueprint',
	'WEAPON_PROXMINE_blueprint',
	'WEAPON_PUMPSHOTGUN_MK2_blueprint',
	'WEAPON_PUMPSHOTGUN_blueprint',
	'WEAPON_REVOLVER_blueprint',
	'WEAPON_SAWNOFFSHOTGUN_blueprint',
	'WEAPON_SMG_MK2_blueprint',
	'WEAPON_SMG_blueprint',
	'WEAPON_SNIPERRIFLE_blueprint',
	'WEAPON_SNSPISTOL_MK2_blueprint',
	'WEAPON_SNSPISTOL_blueprint',
	'WEAPON_SPEACIALCARBINERIFLE_blueprint',
	'WEAPON_SPECIALCARBINE_MK2_blueprint',
	'WEAPON_STICKYBOMB_blueprint',
	'WEAPON_VINTAGEPISTOL_blueprint',
	'alcohol',
	'antidot',
	'bombshell',
	'bread',
	'cloth',
	'emptybottle',
	'gunpower',
	'mgshell',
	'michelin_tires_blueprint',
	'nos_blueprint',
	'oxygenmask_blueprint',
	'pistol_clip',
	'pistolshell',
	'race_brakes_blueprint',
	'race_suspension_blueprint',
	'race_transmition_blueprint',
	'repairkit_blueprint',
	'rifle_clip',
	'rifleshell',
	'rubber',
	'scrap',
	'shell_oil_blueprint',
	'shotgun_clip',
	'shotgunshell',
	'smg_clip',
	'smgshell',
	'sniper_clip',
	'snipershell',
	'turbo_lvl_1_blueprint',
	'v8engine_blueprint',
	'water',
	'wood',
	
}

-- C Class

Config.cweaponn = { -- weapon
}

Config.citemm = { -- item
	'WEAPON_ADVANCEDRIFLE_blueprint',
	'WEAPON_APPISTOL_blueprint',
	'WEAPON_ASSAULTSHOTGUN_blueprint',
	'WEAPON_ASSUALTRIFLE_blueprint',
	'WEAPON_ASSUALTSMG_blueprint',
	'WEAPON_AUTOSHOTGUN_blueprint',
	'WEAPON_BULLPUPRIFLE_MK2_blueprint',
	'WEAPON_BULLPUPRIFLE_blueprint',
	'WEAPON_BULLPUPSHOTGUN_blueprint',
	'WEAPON_BZGAS_blueprint',
	'WEAPON_CARBINERIFLE_MK2_blueprint',
	'WEAPON_CARBINERIFLE_blueprint',
	'WEAPON_CERAMICPISTOL_blueprint',
	'WEAPON_COMBATPDW_blueprint',
	'WEAPON_COMBATPISTOL_blueprint',
	'WEAPON_COMBATSHOTGUN_blueprint',
	'WEAPON_COMPACTRIFLE_blueprint',
	'WEAPON_DBSHOTGUN_blueprint',
	'WEAPON_DOUBLEACTION_blueprint',
	'WEAPON_GRENADE_blueprint',
	'WEAPON_HEAVYPISTOL_blueprint',
	'WEAPON_HEAVYSHOTGUN_blueprint',
	'WEAPON_MACHINEPISTOL_blueprint',
	'WEAPON_MARKSMANPISTOL_blueprint',
	'WEAPON_MICROSMG_blueprint',
	'WEAPON_MILITARYRIFLE_blueprint',
	'WEAPON_MOLOTOV_blueprint',
	'WEAPON_MUSKET_blueprint',
	'WEAPON_NAVYREVOLVER_blueprint',
	'WEAPON_PIPEBOMB_blueprint',
	'WEAPON_PISTOL50_blueprint',
	'WEAPON_PISTOL_blueprint',
	'WEAPON_PROXMINE_blueprint',
	'WEAPON_PUMPSHOTGUN_MK2_blueprint',
	'WEAPON_PUMPSHOTGUN_blueprint',
	'WEAPON_REVOLVER_blueprint',
	'WEAPON_SAWNOFFSHOTGUN_blueprint',
	'WEAPON_SMG_MK2_blueprint',
	'WEAPON_SMG_blueprint',
	'WEAPON_SNSPISTOL_MK2_blueprint',
	'WEAPON_SNSPISTOL_blueprint',
	'WEAPON_SPEACIALCARBINERIFLE_blueprint',
	'WEAPON_SPECIALCARBINE_MK2_blueprint',
	'WEAPON_STICKYBOMB_blueprint',
	'WEAPON_VINTAGEPISTOL_blueprint',
	'alcohol',
	'bombshell',
	'bread',
	'cloth',
	'emptybottle',
	'gunpower',
	'michelin_tires_blueprint',
	'nos_blueprint',
	'oxygenmask_blueprint',
	'pistol_clip',
	'pistolshell',
	'race_suspension_blueprint',
	'race_transmition_blueprint',
	'repairkit_blueprint',
	'rifle_clip',
	'rifleshell',
	'rubber',
	'scrap',
	'shell_oil_blueprint',
	'shotgun_clip',
	'shotgunshell',
	'smg_clip',
	'smgshell',
	'water',
	'wood',
}

-- D Class

Config.dweaponn = { -- weapon
	
}

Config.ditemm = { -- item
	'WEAPON_APPISTOL_blueprint',
	'WEAPON_CERAMICPISTOL_blueprint',
	'WEAPON_COMBATPISTOL_blueprint',
	'WEAPON_HEAVYPISTOL_blueprint',
	'WEAPON_NAVYREVOLVER_blueprint',
	'WEAPON_PISTOL_blueprint',
	'WEAPON_REVOLVER_blueprint',
	'WEAPON_VINTAGEPISTOL_blueprint',
	'alcohol',
	'bread',
	'cloth',
	'emptybottle',
	'gunpower',
	'pistol_clip',
	'pistolshell',
	'rubber',
	'scrap',
	'water',
	'wood',
}

Config.zones = {
	{ ['x'] = 16.86, ['y'] = -641.17, ['z'] = 15.25},
	{ ['x'] = 1699.01, ['y'] = 2603.22, ['z'] = 44.73},
	{ ['x'] = -1136.93, ['y'] = 4921.21, ['z'] = 274.18},
}